# Generated by Django 4.0.4 on 2022-06-09 06:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_payment_stripe_price_id_payment_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addevent',
            name='event_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='addevent',
            name='event_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addevent',
            name='event_location',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addevent',
            name='event_review',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addevent',
            name='event_start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
