# Generated by Django 4.0.4 on 2022-06-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_addevent_event_end_date_addevent_event_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addevent',
            name='event_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
