# Generated by Django 4.0.4 on 2022-06-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_addevent_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addevent',
            name='event_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
