# Generated by Django 4.0.4 on 2022-06-13 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_eventcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.addevent'),
        ),
    ]
