# Generated by Django 4.0.4 on 2022-06-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_addevent_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcomment',
            name='new_comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
