# Generated by Django 4.0.4 on 2022-06-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_eventcomment_new_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Payment_status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
